// this class uses parameters in it's declaration which become properties
class Person(var firstName: String, var lastName: String, var age: Int) {

    // properties
    // belongsTo has getter and setter autogenerated
    var belongsTo: String = "Mystery Inc."    
    // address is an example of explicit supply of getter and setter
    // in this case the setter is private, note the user of the backing
    // field with the name/identifier field which can only be used in 
    // the property accessors
    var address: String = "The Mystery Machine"
        get() = field
        private set(value) { field = value }

    // functions
    fun debug() {
        println("$firstName belongs to $belongsTo annd address of $address")
    }
}

fun main() {
    var person = Person("Scooby", "Doo", 10)
    person.firstName = "Scrappy"
    person.debug()
}
